//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteContselfSistema.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class FuncionariosTeste
    {
        public int CodFuncionario { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public decimal Salario { get; set; }
        public string Atividades { get; set; }
    }
}

